---

- include: preflight.yml

- include: install.yml

- name: ensure alertmanager_bot service is started and enabled
  systemd:
    name: "{{ alertmanager_bot_service_name }}"
    state: started
    enabled: true
